import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "CV", description: "Curriculum vitae of Osita Ukwuaba." };
const skills=["Python","PyTorch","snnTorch","TensorFlow","scikit-learn","C++","Docker","Git","AWS","SQL","React"];
export default function CV(){return <main className="cv-page"><header className="cv-header"><Link href="/" className="wordmark"><span className="wordmark-mark">OU</span><span>Osita Ukwuaba</span></Link><Link href="/" className="back-link">← Back to research site</Link></header><div className="cv-shell">
  <section className="cv-hero"><p className="eyebrow">Curriculum vitae</p><h1>Osita Ukwuaba</h1><p>PhD Student, Electrical &amp; Computer Engineering<br/>Rochester Institute of Technology</p><div className="cv-links"><a href="mailto:ou1684@rit.edu">ou1684@rit.edu</a><a href="https://www.linkedin.com/in/osita-ukwuaba/">LinkedIn</a><a href="https://github.com/ositaukwuaba">GitHub</a></div></section>
  <CVSection title="Profile"><p>PhD researcher developing testing and evaluation methods for dependable AI systems, with primary emphasis on spiking neural networks, neuromorphic computing, fault tolerance, and safety-relevant system behavior.</p></CVSection>
  <CVSection title="Education"><CVItem date="2024—2028 (expected)" title="PhD, Electrical & Computer Engineering" org="Rochester Institute of Technology" text="Research: trustworthy neuromorphic computing; testing and reliability of spiking neural networks."/><CVItem date="2019—2022" title="MS, Computer Science" org="Georgia Institute of Technology" text="Artificial intelligence, deep learning, healthcare analytics, and human–computer interaction."/><CVItem date="2003—2008" title="B.Eng., Electronic Engineering" org="University of Nigeria, Nsukka"/></CVSection>
  <CVSection title="Research experience"><CVItem date="2024—Present" title="Research Assistant · Brain Lab" org="Rochester Institute of Technology" text="Developing testing and evaluation frameworks for spiking neural networks to improve the reliability, fault tolerance, and performance of neuromorphic systems."/><CVItem date="2020—2022" title="Research Assistant · Design & Intelligence Laboratory" org="Georgia Institute of Technology" text="Researched social-agent mediated interaction in the NSF AI-ALOE Institute; developed ML models from learner interaction data and investigated cognitive approaches to human–agent understanding."/></CVSection>
  <CVSection title="Publication"><CVItem date="2026" title="Timing Matters: Delay Fault Characterization and Testing in SNN Accelerators" org="GLSVLSI ’26 · Osita Ukwuaba and Cory Merkel" text="DOI: 10.1145/3787109.3815284" link="https://dl.acm.org/doi/10.1145/3787109.3815284"/></CVSection>
  <CVSection title="Selected research projects"><CVItem date="2024—Present" title="Resource-Optimized Testing of Spiking Neural Networks" text="Efficient approaches for evaluating the dependability of neuromorphic systems under hardware faults."/><CVItem date="Current" title="Fault-Aware Continual Learning in SNNs" text="Improving the reliability of spiking neural networks that learn continually in imperfect and changing environments."/><CVItem date="Current" title="AI Control and Evaluation" text="Evaluating practical approaches for dependable oversight and intervention in increasingly capable AI systems."/><CVItem date="2024" title="Comparative Evaluation of LLM Risk" text="BlueDot-funded project examining evaluation design and safety-benchmark limitations across bio, cyber, and chemical risk domains."/></CVSection>
  <CVSection title="Engineering experience"><CVItem date="2015—2024" title="Co-Founder & Full-Stack Engineer" org="Orprise Solutions" text="Led product development and delivered full-stack software and ML-enabled analytics systems."/><CVItem date="2010—2015" title="Program Analyst & IT Director" org="Loyola Jesuit College" text="Designed and delivered institutional information systems serving more than 5,000 users."/></CVSection>
  <CVSection title="Training"><CVItem date="2024" title="Technical AI Safety" org="BlueDot Impact · Certificate of Completion"/></CVSection><CVSection title="Technical skills"><div className="cv-skills">{skills.map(s=><span key={s}>{s}</span>)}</div></CVSection>
</div></main>}
function CVSection({title,children}:{title:string;children:React.ReactNode}){return <section className="cv-section"><h2>{title}</h2><div>{children}</div></section>}
function CVItem({date,title,org,text,link}:{date:string;title:string;org?:string;text?:string;link?:string}){return <article className="cv-item"><time>{date}</time><div><h3>{link?<a href={link}>{title} ↗</a>:title}</h3>{org&&<strong>{org}</strong>}{text&&<p>{text}</p>}</div></article>}
